name: Build WMVx

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download the VSIX file
        run: |
          curl -L -o QtVisualStudioTools2022.vsix "https://marketplace.visualstudio.com/_apis/public/gallery/publishers/TheQtCompany/vsextensions/QtVisualStudioTools2022/3.3.0.13/vspackage"

      - name: Install the Visual Studio extension
        run: |
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\VSIXInstaller.exe" QtVisualStudioTools2022.vsix
        # Update the path if you're using a different edition (Community, Professional, etc.)

      - name: Verify installation
        run: |
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe" /setup

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5'
          host: 'windows'
          target: 'desktop'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build solution
        run: |
          msbuild WMVx.sln /p:Configuration=Release /p:Platform=x64
