name: Build WMVx

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      #- name: "Install QT Visual Studio Tools 2022" 
      #  uses: microcompiler/install-vsix@main
      #  with: 
      #    packagename: 'TheQtCompany.QtVisualStudioTools2022'

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5'
          host: 'windows'
          target: 'desktop'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build solution
        run: |
          msbuild WMVx.sln /p:Configuration=Release /p:Platform=x64
